version: '2'
services:
  web:
    build: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
      - ./src:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: quiz
      MYSQL_USER: php
      MYSQL_PASSWORD: 1234php
      MYSQL_ROOT_PASSWORD: 1234php
    ports:
      - "3306:3306"



